= Space Shooter

== Issues
Boring

But served its purpose


== How to install

First install CMake Version >= 3.22, Then Download SFML >= 2.5 :

(Windows) https://www.sfml-dev.org/download/sfml/2.5.1/

Then Extract SFML to Anywhere on your PC, Then add SFML_ROOT Variable in your User's Environment variables not the system's
 with the value being the path to libraries root folder, the folder that has libs folder in it, Then build the project with CMake
, Then Copy All of the SFML dll files from SFML_ROOT\bin folder to where the built exe file is, then copy the assets folder to where the exe file built is.

(MacOS) brew install sfml, Then Build the project with cmake, then copy the assets folder to where the built executable file is.

(Linux) Your system's Package manager, Then Build the project with cmake, then copy the assets folder to where the built executable file is.

== Controls

Up Arrow Go up in the menu

Down Arrow Go down in the menu

A for Steering the ship to left

D for Steering the ship to Right

Space for Shooting

== Credits
SFML: https://www.sfml-dev.org

Uses Unifont

Textures:

(Partially): https://www.raywenderlich.com/2642-how-to-make-a-game-like-space-invaders-with-sprite-kit-tutorial-part-1#toc-anchor-001

and: https://github.com/DamirSvrtan/space-invaders.rb

== License
The Unlicense
